Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2019-08, with the labels that each got.

#1096 Grant all tables in schema fixup
  manifests/server/grant.pp
  spec/acceptance/server/grant_spec.rb
Labels: bugfix

#1089 Fix/directory defined twice
  manifests/globals.pp
  manifests/params.pp
  manifests/server.pp
  manifests/server/initdb.pp
  manifests/server/tablespace.pp
  spec/unit/classes/server/initdb_spec.rb
  spec/unit/classes/server_spec.rb
  spec/unit/defines/server/extension_spec.rb
  spec/unit/defines/server/tablespace_spec.rb
Labels: bugfix, feature

#1100 pdksync - MODULES-9692 - pdksync_1.12.0-0-g55d9ae2
  Gemfile
  metadata.json
Labels: maintenance

#1099 (MODULES-9658) - custom ports are not labeled correctly
  README.md
  manifests/globals.pp
  manifests/params.pp
  manifests/server.pp
  manifests/server/config.pp
  spec/acceptance/alternative_port_spec.rb
  spec/unit/classes/server/config_spec.rb
Labels: bugfix

#1093 (MODULES-9219) - puppetlabs-postgresql : catalog compilation fails when the service command is not installed
  manifests/params.pp
Labels: bugfix
