Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2019-03, with the labels that each got.

#1064 pdksync - Remove .project from .gitignore
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .sync.yml
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#1063 change username/group/datadir defaults for FreeBSD
  manifests/params.pp
Labels: bugfix

#1044 (maint) remove inconsistent extra variable
  manifests/server.pp
Labels: backwards-incompatible
