Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2020-04, with the labels that each got.

#1158 add version configs for SLES 12 SP 3 to 5
  manifests/globals.pp
Labels: feature

#1160 (MODULES-10610) Use correct lower bound for concat version
  metadata.json
Labels: backwards-incompatible

#1166 pdksync - Add dependency gems to development group
  Gemfile
Labels: maintenance

#1168 Mark version param as deprecated in server.pp comments
  manifests/server.pp
Labels: maintenance

#1167 service_ensure => true is now an allowed value (aliased to running)
  manifests/server/service.pp
  spec/unit/classes/server_spec.rb
Labels: feature
