Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2020-11, with the labels that each got.

#1202 Set default PostgreSQL version for Fedora 33
  manifests/globals.pp
Labels: maintenance

#1204 Use non-deprecation password function in acceptance tests
  spec/acceptance/overridden_settings_spec.rb
  spec/acceptance/postgresql_conn_validator_spec.rb
  spec/acceptance/server/grant_role_spec.rb
  spec/acceptance/server/grant_spec.rb
  spec/acceptance/server/reassign_owned_by_spec.rb
  spec/acceptance/server/schema_spec.rb
  spec/acceptance/sql_task_spec.rb
Labels: maintenance

#1205 (IAC-1000) - Removal of inappropriate terminology
  .github/workflows/release.yml
  .github/workflows/weekly.yml
  CONTRIBUTING.md
  README.md
  REFERENCE.md
  lib/puppet/type/postgresql_replication_slot.rb
  metadata.json
  readmes/README_ja_JP.md
Labels: maintenance

#1209 (IAC-1189) - Fix for SLES 15 SP 1 and later
  manifests/globals.pp
Labels: bugfix

#1199 Manage postgresql_conf_path file permissions
  manifests/globals.pp
  manifests/params.pp
  manifests/server.pp
  manifests/server/config.pp
  spec/acceptance/server/config_entry_spec.rb
Labels: feature

#1211 pdksync - (maint) Add release_checks_7 config to provision.yaml
  provision.yaml
Labels: maintenance
