Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2020-12, with the labels that each got.

#1212 (maint) updated defaults for rhel7 policycoreutils
  manifests/server/config.pp
  spec/unit/classes/server/config_spec.rb
Labels: bugfix

#1201 Change - Use systemd drop-in directory for unit overrides
  manifests/server/config.pp
  spec/unit/classes/server/config_spec.rb
  spec/unit/defines/server/config_entry_spec.rb
  templates/systemd-override.erb
Labels: bugfix

#1217 pdksync - Remove EL6 testing from Travis
  .sync.yml
  .travis.yml
  provision.yaml
Labels: maintenance

#1215 pdksync - (feat) - Add support for puppet 7
  metadata.json
Labels: feature

#1207 (maint) add postgresql module to ci
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .github/workflows/release.yml
  .github/workflows/weekly.yml
  .pdkignore
  .rubocop.yml
  .rubocop_todo.yml
  .sync.yml
  .travis.yml
  Gemfile
  lib/puppet/functions/postgresql/postgresql_acls_to_resources_hash.rb
  lib/puppet/functions/postgresql/postgresql_escape.rb
  lib/puppet/provider/postgresql_replication_slot/ruby.rb
  lib/puppet/type/postgresql_psql.rb
  lib/puppet/util/postgresql_validator.rb
  metadata.json
  spec/acceptance/alternative_port_spec.rb
  spec/acceptance/server/grant_role_spec.rb
  spec/acceptance/server/grant_spec.rb
  spec/acceptance/server/reassign_owned_by_spec.rb
  spec/acceptance/server/recovery_spec.rb
  spec/acceptance/sql_task_spec.rb
  spec/acceptance/utf8_encoding_spec.rb
  spec/acceptance/z_alternative_pgdata_spec.rb
  spec/spec_helper_acceptance_local.rb
  spec/unit/puppet/provider/postgresql_replication_slot/ruby_spec.rb
  spec/unit/puppet/type/postgresql_conn_validator.rb
  spec/unit/puppet/type/postgresql_psql_spec.rb
  spec/unit/type/postgresql_conf_spec.rb
Labels: maintenance

#1221 (IAC-1351) Remove CentOS 5 & RHEL 5 from provision.yaml file
  provision.yaml
Labels: maintenance
