Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2020-05, with the labels that each got.

#1170 (IAC-794) - v6.5.0 Release Mergeback
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#1169 pdksync - (maint) - Pdk Update
  .rubocop.yml
  .vscode/extensions.json
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#1171 pdksync - Use abs instead of vmpooler to provision test resources
  provision.yaml
  spec/spec_helper_acceptance.rb
Labels: maintenance

#1172 (IAC-746) - Add ubuntu 20.04 support
  .github/workflows/release.yml
  .github/workflows/weekly.yml
  .sync.yml
  .travis.yml
  manifests/globals.pp
  metadata.json
  provision.yaml
Labels: feature

#1165 Fix custom port in extension
  manifests/server/extension.pp
  spec/unit/defines/server/extension_spec.rb
Labels: bugfix
