Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2020-02, with the labels that each got.

#1135 Treat $version as an integer for comparison, defaults to string
  manifests/server/config.pp
Labels: bugfix

#1137 Correct versioncmp logic in config.pp
  manifests/server/config.pp
Labels: bugfix

#1136 feat: enable different database resource name in extension
  manifests/server/extension.pp
Labels: feature

#1092 (MAINT) Add a default function
  REFERENCE.md
  functions/default.pp
  manifests/server/extension.pp
  spec/unit/defines/server/extension_spec.rb
  spec/unit/defines/server/role_spec.rb
Labels: maintenance

#1138 (IAC-365) updating tokens and dataset for honeycomb
  .github/workflows/release.yml
  .sync.yml
  .travis.yml
  Gemfile
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#1140 pdksync - (IAC-215) - Implement use_litmus:true
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#1143 Fix compare link in the Changelog
  CHANGELOG.md
Labels: maintenance

#1141 Add Fedora 31 compatibility
  manifests/globals.pp
Labels: feature

#1145 (IAC-527) fix selinux test idempotency
  .sync.yml
  .travis.yml
  metadata.json
  provision.yaml
  spec/acceptance/alternative_port_spec.rb
  spec/acceptance/db_spec.rb
  spec/acceptance/default_parameters_spec.rb
  spec/acceptance/overridden_settings_spec.rb
  spec/acceptance/postgresql_conn_validator_spec.rb
  spec/acceptance/postgresql_psql_spec.rb
  spec/acceptance/server/grant_role_spec.rb
  spec/acceptance/server/grant_spec.rb
  spec/acceptance/server/reassign_owned_by_spec.rb
  spec/acceptance/server/recovery_spec.rb
  spec/acceptance/server/schema_spec.rb
  spec/acceptance/utf8_encoding_spec.rb
  spec/acceptance/z_alternative_pgdata_spec.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#1149 pdksync - (maint) - Pdk Update
  metadata.json
Labels: maintenance
