Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2020-09, with the labels that each got.

#1189 Release MergeBack v6.7.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#1194 (IAC-1136) Back out CentOS 8 tests
  .travis.yml
Labels: maintenance

#1192 (maint) Fix typo in provision.yaml
  provision.yaml
Labels: maintenance

#1193 (maint) Use 'policycoreutils-python-utils' on RHEL 8
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#1187 Allow removal of config_entries via main class
  manifests/server.pp
  spec/unit/classes/server_spec.rb
Labels: feature

#1188 Fix contrib package name under debian 10
  manifests/params.pp
Labels: bugfix

#1195 add hostgssenc type to pg_hba rules
  manifests/server/pg_hba_rule.pp
Labels: feature

#1196 Fix incorrect guard clause logic
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#1197 Release mergeback version 6.8.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance
