Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2021-06, with the labels that each got.

#1278 pdksync - (maint) PDKSync - PDK Update
  .github/workflows/auto_release.yml
  .github/workflows/release.yml
  .github/workflows/spec.yml
  .pdkignore
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#1267 MODULES-11049 - Implement default privileges changes
  README.md
  manifests/server/default_privileges.pp
  spec/acceptance/server/default_privileges_spec.rb
  spec/unit/defines/server/default_privileges_spec.rb
Labels: feature

#1276 (MODULES-8700) Autorequire the service in postgresql_psql
  lib/puppet/type/postgresql_psql.rb
  spec/unit/defines/server/database_spec.rb
  spec/unit/defines/server/grant_spec.rb
  spec/unit/defines/server/reassign_owned_by_spec.rb
  spec/unit/defines/server/role_spec.rb
  spec/unit/defines/server/tablespace_spec.rb
Labels: bugfix

#1281 (maint) update test with the changes from Autorequire the service
  spec/unit/defines/server/default_privileges_spec.rb
Labels: maintenance
