Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2021-03, with the labels that each got.

#1244 (maint) Update major dependencies prior to release
  metadata.json
Labels: maintenance

#1246 pdksync - (MAINT) Remove RHEL 5 family support
  metadata.json
Labels: backwards-incompatible

#1247 pdksync - (MAINT) Remove SLES 11 support
  metadata.json
Labels: backwards-incompatible

#1239 Add DNF module management
  manifests/dnfmodule.pp
  manifests/globals.pp
  manifests/params.pp
  spec/unit/classes/client_spec.rb
  spec/unit/classes/server_spec.rb
Labels: feature

#1248 pdksync - (MAINT) PDK update for GHA workflows + Litmus updates
  .github/workflows/auto_release.yml
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  metadata.json
Labels: maintenance

#1252 (IAC-1525) Release mergeback version v7.0.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#1253 Ensure port is a string in psql command
  lib/puppet/provider/postgresql_psql/ruby.rb
Labels: bugfix

#1255 (IAC-1533) Release version v7.0.1
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1256 (IAC-1533) - Release v7.0.1 Merge Back
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1258 (MODULES-10957) Override the set_sensitive_parameters method
  lib/puppet/type/postgresql_psql.rb
Labels: bugfix

#1259 (IAC-1548) Release version v7.0.2
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1260 (IAC-1548) - v7.0.2 Merge Back
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1261 pdksync - PDK Update - Replace Travis and Appveyor with Github Actions
  .github/workflows/auto_release.yml
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .github/workflows/release.yml
  .github/workflows/spec.yml
  .pdkignore
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance
