Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2021-02, with the labels that each got.

#1225 Clean up globals logic to support CentOS 8 stream
  manifests/globals.pp
  manifests/params.pp
  manifests/server/config.pp
  manifests/server/config_entry.pp
  manifests/server/initdb.pp
  spec/unit/classes/client_spec.rb
  spec/unit/classes/globals_spec.rb
  spec/unit/classes/lib/devel_spec.rb
  spec/unit/classes/lib/java_spec.rb
  spec/unit/classes/lib/perl_spec.rb
  spec/unit/classes/lib/pgdocs_spec.rb
  spec/unit/classes/lib/python_spec.rb
  spec/unit/classes/params_spec.rb
  spec/unit/classes/server/contrib_spec.rb
  spec/unit/classes/server/initdb_spec.rb
  spec/unit/classes/server/plperl_spec.rb
  spec/unit/classes/server/plpython_spec.rb
  spec/unit/classes/server/postgis_spec.rb
  spec/unit/defines/server/config_entry_spec.rb
  spec/unit/defines/server/database_grant_spec.rb
  spec/unit/defines/server/database_spec.rb
  spec/unit/defines/server/db_spec.rb
  spec/unit/defines/server/extension_spec.rb
  spec/unit/defines/server/grant_role_spec.rb
  spec/unit/defines/server/grant_spec.rb
  spec/unit/defines/server/pg_hba_rule_spec.rb
  spec/unit/defines/server/pg_ident_rule_spec.rb
  spec/unit/defines/server/reassign_owned_by_spec.rb
  spec/unit/defines/server/recovery_spec.rb
  spec/unit/defines/server/role_spec.rb
  spec/unit/defines/server/schema_spec.rb
  spec/unit/defines/server/table_grant_spec.rb
  spec/unit/defines/server/tablespace_spec.rb
  spec/unit/defines/validate_db_connection_spec.rb
Labels: feature

#1226 Fix postgresql::sql task when password is not set
  tasks/sql.rb
Labels: bugfix

#1229 pdksync - Update gha templates
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  Gemfile
  Rakefile
  metadata.json
Labels: maintenance

#1231 (IAC-1136) Back out CentOS 8 tests on TravisCI
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#1230 (bug) reload the service after the deletion of old unit file
  manifests/server/config.pp
Labels: bugfix

#1233 Also perform systemd daemon-reload on Puppet 6.1+
  manifests/server/config.pp
Labels: bugfix

#1232 (IAC-1408) Release Prep v6.10.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1234 (IAC-1408) Release mergeback v6.10.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1206 pdksync - Update pdk-templates for gitpod and codespaces support
  .github/workflows/auto_release.yml
  .gitpod.Dockerfile
  .gitpod.yml
  .sync.yml
  metadata.json
Labels: maintenance

#1235 (IAC-1421) Release Prep v6.10.1
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1236 (IAC-1422) - v6.10.1 Release Mergeback
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1240 Fix command shell escaping
  lib/puppet/provider/postgresql_psql/ruby.rb
  lib/puppet/type/postgresql_psql.rb
  lib/puppet/util/postgresql_validator.rb
  manifests/server/role.pp
  spec/acceptance/postgresql_psql_spec.rb
  spec/spec_helper_local.rb
  spec/unit/defines/server/role_spec.rb
  spec/unit/puppet/provider/postgresql_conn_validator/ruby_spec.rb
  spec/unit/puppet/provider/postgresql_psql/ruby_spec.rb
  tasks/sql.rb
Labels: bugfix

#1242 (IAC-1475) Release Prep v6.10.2
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#1243 Release merge-back v6.10.2
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#1238 pdksync - Remove Puppet 5 from testing and bump minimal version to 6.0.0
  .github/workflows/auto_release.yml
  .rubocop.yml
  .sync.yml
  .travis.yml
  metadata.json
  provision.yaml
Labels: backwards-incompatible
