Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2021-08, with the labels that each got.

#1285 (maint) - Set max_issues for changelog generator to 500
  .sync.yml
  Rakefile
Labels: maintenance

#1288 pdksync - (IAC-1709) - Add Support for Debian 11
  manifests/globals.pp
  metadata.json
Labels: feature

#1290 drop code for Debian 6/7 and Ubuntu 10.04/12.04
  manifests/globals.pp
  manifests/server/config_entry.pp
  manifests/server/initdb.pp
  spec/unit/defines/server/extension_spec.rb
Labels: bugfix

#1293 (maint) Allow stdlib 8.0.0
  metadata.json
Labels: feature
