Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2022-08, with the labels that each got.

#1348 Ensure multiple postgresql::server::recovery resources can be defined
  manifests/server/recovery.pp
  spec/defines/server/recovery_spec.rb
Labels: bugfix, community

#1355 pdksync - (GH-cat-11) Certify Support for Ubuntu 22.04
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  metadata.json
Labels: feature

#1319 (MODULES-11251) Add support for backup provider "pg_dump"
  .fixtures.yml
  README.md
  manifests/backup/pg_dump.pp
  manifests/params.pp
  manifests/server.pp
  spec/classes/server_spec.rb
  templates/pg_dump.sh.epp
Labels: community

#1357 Use version 9 of apt module
  metadata.json
Labels: maintenance

#1356 Only require password when used
  manifests/server/db.pp
Labels: bugfix, community

#1361 (GH-1360) Reverting REFERENCE.md changes
  REFERENCE.md
Labels: bugfix

#1363 Fix puppet-strings documentation
  REFERENCE.md
  manifests/server.pp
Labels: bugfix, community
