Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2022-10, with the labels that each got.

#1368 pdksync - (CONT-130) - Dropping Support for Debian 9
  metadata.json
Labels: bugfix, hacktoberfest

#1370 pdksync - (PDKSync) Removal of puppet_module_gems
  .devcontainer/README.md
  .sync.yml
  Gemfile
  metadata.json
Labels: maintenance, hacktoberfest

#1371 pdksync - (CONT-189) Remove support for RedHat6 / OracleLinux6 / Scientific6
  metadata.json
  spec/classes/lib/devel_spec.rb
  spec/defines/server/config_entry_spec.rb
  spec/spec_helper_local.rb
Labels: bugfix, hacktoberfest

#1372 pg_hba_rule does not properly verify address parameter
  manifests/backup/pg_dump.pp
  manifests/server/default_privileges.pp
  manifests/server/grant.pp
  manifests/server/pg_hba_rule.pp
  manifests/server/role.pp
  spec/defines/server/pg_hba_rule_spec.rb
  types/pg_hba_rule_address.pp
Labels: feature, community

#1375 pg_hba_rule: Move `type` datatype to own type
  manifests/server/pg_hba_rule.pp
  spec/type_aliases/pg_hba_rule_type_spec.rb
  types/pg_hba_rule_type.pp
Labels: feature, community

#1374 Rewrite dependency installation using native Puppet
  spec/spec_helper_acceptance_local.rb
Labels: community
