Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2022-07, with the labels that each got.

#1350 Add version for Ubuntu 22.04
  manifests/globals.pp
Labels: bugfix, community

#1351 Respect $service_status on Red Hat-based distros
  manifests/params.pp
Labels: community

#1349 Fix service status detection on Debian-based OSes
  manifests/params.pp
  spec/classes/server/service_spec.rb
  spec/classes/server_spec.rb
Labels: feature, community

#1353 (GH-1352) - Updating postgresql service version on SLES
  manifests/globals.pp
Labels: bugfix
