Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2023-11, with the labels that each got.

#1549 pdksync - [CAT-1541]: Adding github directory to pdkignore
  .pdkignore
Labels: maintenance

#1551 Unconfine postgresql_conf
  lib/puppet/provider/postgresql_conf/ruby.rb
Labels: bugfix, community

#1553 pdksync - 'CAT-945 - Update README.md LICENSE'
  README.md
Labels: maintenance

#1557 (#1556) Fix Python package name for Ubuntu >= 22.04
  manifests/params.pp
Labels: community
