Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2023-08, with the labels that each got.

#1463 pdksync - (CAT-343) Audit modules and tools for references to travis. Removed all needless references to travis.
  README.md
  provision.yaml
Labels: maintenance

#1471 port parameter: Cleanup datatype
  REFERENCE.md
  manifests/server.pp
  manifests/server/default_privileges.pp
  manifests/server/extension.pp
  manifests/server/grant.pp
  manifests/server/grant_role.pp
  manifests/server/instance/config.pp
  manifests/server/instance/late_initdb.pp
  manifests/server/instance/passwd.pp
  manifests/server/instance/service.pp
  manifests/server/reassign_owned_by.pp
  manifests/server/role.pp
  manifests/server/table_grant.pp
Labels: community

#1472 pg_hba.conf: Introduce a newline after each rule
  templates/pg_hba_rule.conf.epp
Labels: community

#1475 reassign_owned_by: Cleanup puppet-strings documentation
  manifests/server/reassign_owned_by.pp
Labels: community

#1474 port parameter: log warning when its a string
  manifests/server.pp
  manifests/server/default_privileges.pp
  manifests/server/extension.pp
  manifests/server/grant.pp
  manifests/server/grant_role.pp
  manifests/server/instance/config.pp
  manifests/server/instance/late_initdb.pp
  manifests/server/instance/passwd.pp
  manifests/server/instance/service.pp
  manifests/server/instance/systemd.pp
  manifests/server/reassign_owned_by.pp
  manifests/server/role.pp
  manifests/server/table_grant.pp
  spec/acceptance/alternative_port_spec.rb
  spec/defines/server/extension_spec.rb
  spec/defines/server/grant_role_spec.rb
Labels: community

#1480 Revert "puppetlabs/stdlib: Require 9.x"
  manifests/backup/pg_dump.pp
  manifests/server/extension.pp
  manifests/server/instance/config.pp
  manifests/server/instance/passwd.pp
  metadata.json
Labels: maintenance

#1482 postgresql::server: Remove deprecated version parameter
  REFERENCE.md
  manifests/server.pp
Labels: backwards-incompatible, community

#1473 port: Enforce Stdlib::Port datatype
  REFERENCE.md
  manifests/server.pp
  manifests/server/default_privileges.pp
  manifests/server/extension.pp
  manifests/server/grant.pp
  manifests/server/grant_role.pp
  manifests/server/instance/config.pp
  manifests/server/instance/late_initdb.pp
  manifests/server/instance/passwd.pp
  manifests/server/instance/service.pp
  manifests/server/instance/systemd.pp
  manifests/server/reassign_owned_by.pp
  manifests/server/role.pp
  manifests/server/table_grant.pp
  templates/systemd-override.conf.epp
Labels: backwards-incompatible, community

#1481 puppetlabs/stdlib: Require 9.x
  manifests/backup/pg_dump.pp
  manifests/server/extension.pp
  manifests/server/instance/config.pp
  manifests/server/instance/passwd.pp
  metadata.json
Labels: backwards-incompatible, community

#1483 postgresql::server: Remove deprecated createdb_path parameter
  REFERENCE.md
  manifests/globals.pp
  manifests/server.pp
  manifests/server/database.pp
Labels: backwards-incompatible, community

#1484 Delete deprecated validate_db_connection() defined resource
  REFERENCE.md
  manifests/validate_db_connection.pp
  spec/defines/validate_db_connection_spec.rb
Labels: backwards-incompatible, community

#1485 Delete legacy readmes/README_ja_JP.md
  readmes/README_ja_JP.md
Labels: community

#1486 Drop postgresql 8.1/RHEL5 specific code
  manifests/globals.pp
  manifests/server/database.pp
  manifests/server/instance/config.pp
  manifests/server/pg_hba_rule.pp
  spec/acceptance/db_spec.rb
  spec/acceptance/server/grant_role_spec.rb
  spec/acceptance/server/schema_spec.rb
Labels: backwards-incompatible, community

#1489 Drop postgresql 8.4/RHEL6 specific code
  manifests/globals.pp
  manifests/server/pg_hba_rule.pp
  spec/acceptance/server/grant_spec.rb
Labels: backwards-incompatible, community

#1487 Cleanup useless $connect_setting validation
  manifests/server/database.pp
  manifests/server/default_privileges.pp
  manifests/server/extension.pp
  manifests/server/grant.pp
  manifests/server/grant_role.pp
  manifests/server/reassign_owned_by.pp
  manifests/server/role.pp
  manifests/server/schema.pp
  manifests/server/tablespace.pp
Labels: community

#1490 Provide a default for config_entry's path and enforce absolute path
  manifests/server/config_entry.pp
Labels: feature, community

#1491 Enforce Stdlib::Absolutepath for filepaths
  manifests/globals.pp
  manifests/server.pp
  manifests/server/default_privileges.pp
  manifests/server/grant.pp
  manifests/server/instance/config.pp
  manifests/server/instance/initdb.pp
  manifests/server/instance/late_initdb.pp
  manifests/server/instance/passwd.pp
  manifests/server/instance/service.pp
  manifests/server/pg_ident_rule.pp
  manifests/server/recovery.pp
  manifests/server/role.pp
Labels: community

#1492 server::database: make user/group/psql_path/default_db configureable
  manifests/server/database.pp
Labels: feature, community

#1496 server::grant: Prefer $connect_settings over default port
  REFERENCE.md
  manifests/server/grant.pp
Labels: bugfix, community

#1497 server::extension: make user/group/psql_path configureable
  manifests/server/extension.pp
Labels: community

#1493 server::database_grant: Always set default user/group and expose port as parameter
  REFERENCE.md
  manifests/server/database_grant.pp
  spec/defines/server/database_grant_spec.rb
Labels: feature, community

#1494 server::db: Make port/user/group configureable
  REFERENCE.md
  manifests/server/db.pp
  spec/defines/server/db_spec.rb
Labels: feature, community
