Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2023-06, with the labels that each got.

#1440 pdksync - (MAINT) - Update Stdlib dependency
  metadata.json
Labels: maintenance

#1441 Update CODEOWNERS
  CODEOWNERS
Labels: maintenance

#1447 pdksync - (CONT-990) - Adding Community Pull Requests template
  .github/pull_request_template.md
Labels: maintenance

#1446 (CONT-347) - correct centos/alma/rocky 8 hanging tests
  spec/acceptance/db_spec.rb
  spec/acceptance/default_parameters_spec.rb
  spec/acceptance/overridden_settings_spec.rb
  spec/acceptance/server/config_entry_spec.rb
Labels: maintenance

#1449 puppetlabs/stdlib: Require 9.x
  manifests/backup/pg_dump.pp
  manifests/server/extension.pp
  manifests/server/instance/config.pp
  manifests/server/instance/passwd.pp
  metadata.json
Labels: backwards-incompatible, community

#1448 puppet/systemd: Allow 5.x & puppetlabs/concat: Allow 9.x
  metadata.json
Labels: feature, community

#1453 (CONT-1180) - Fixing build failures caused by SUSE 15 SP4
  spec/spec_helper_acceptance_local.rb
Labels: maintenance
