Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2023-09, with the labels that each got.

#1499 set datatype for directories to Stdlib::Absolutepath
  manifests/globals.pp
  manifests/server.pp
  manifests/server/instance/config.pp
  manifests/server/instance/initdb.pp
  manifests/server/instance/late_initdb.pp
  manifests/server/instance/passwd.pp
Labels: backwards-incompatible, community

#1501 pdksync - (CAT-1366) - Fix issue url from old jira to github
  metadata.json
Labels: maintenance

#1500 Update REFERENCE.md
  REFERENCE.md
Labels: maintenance, community

#1505 puppet/systemd: Allow 6.x
  metadata.json
Labels: community

#1498 Prefer $connect_settings over explicit parameters
  README.md
  REFERENCE.md
  manifests/server/database.pp
  manifests/server/database_grant.pp
  manifests/server/default_privileges.pp
  manifests/server/extension.pp
  manifests/server/grant.pp
  manifests/server/reassign_owned_by.pp
  manifests/server/role.pp
  manifests/server/schema.pp
  manifests/server/tablespace.pp
  spec/defines/server/database_grant_spec.rb
  spec/defines/server/database_spec.rb
  spec/defines/server/db_spec.rb
  spec/defines/server/default_privileges_spec.rb
  spec/defines/server/extension_spec.rb
  spec/defines/server/grant_spec.rb
Labels: community

#1504 service name should be unique to allow instances
  lib/puppet/type/postgresql_psql.rb
  manifests/server/instance/service.pp
  spec/classes/server/service_spec.rb
  spec/classes/server_spec.rb
  spec/defines/server/database_spec.rb
  spec/defines/server/default_privileges_spec.rb
  spec/defines/server/grant_spec.rb
  spec/defines/server/reassign_owned_by_spec.rb
  spec/defines/server/role_spec.rb
  spec/defines/server/tablespace_spec.rb
Labels: bugfix, community

#1503 unique resource titles to allow multiple instances
  manifests/server/instance/initdb.pp
  manifests/server/instance/passwd.pp
  manifests/server/instance/reload.pp
  spec/classes/server/initdb_spec.rb
  spec/classes/server_spec.rb
Labels: community

#1506 server::schema: Drop unused $version variable
  manifests/server/schema.pp
Labels: feature, community

#1508 PDK update 2.7.0->3.0.0
  .gitignore
  .pdkignore
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Rakefile
  lib/puppet/type/postgresql_psql.rb
  metadata.json
  spec/default_facts.yml
  spec/spec_helper.rb
  spec/spec_helper_local.rb
Labels: feature, community

#1509 server::instance::initdb: simplify if condition
  manifests/server/instance/initdb.pp
Labels: maintenance, community

#1511 spec file: remove ruby shebang
  spec/unit/type/postgresql_conf_spec.rb
Labels: maintenance, community

#1510 add port and psql_path parameter to initdb define
  REFERENCE.md
  manifests/server/instance/initdb.pp
Labels: community

#1512 Flexible password encryption in pg hba conf
  REFERENCE.md
  lib/puppet/functions/postgresql/postgresql_password.rb
  manifests/params.pp
  manifests/server.pp
  manifests/server/instance/config.pp
  spec/acceptance/overridden_settings_spec.rb
  spec/functions/postgresql_password_spec.rb
  spec/functions/postgresql_postgresql_password_spec.rb
Labels: bugfix, community

#1513 spec file: remove ruby shebang
  spec/unit/puppet/type/postgresql_conn_validator.rb
Labels: maintenance, community

#1515 Fix password_encryption for DBVERSION in server::role
  manifests/server/role.pp
  spec/acceptance/server/role_spec.rb
Labels: bugfix, community

#1516 add $manage_selinux as a parameter, keep default, simpler condition
  REFERENCE.md
  manifests/server/instance/config.pp
Labels: feature, community

#1519 Drop EoL FreeBSD 9.4/9.5 specific code
  manifests/params.pp
Labels: feature, community

#1520 Drop EoL SLES 11.4 code
  manifests/params.pp
Labels: community

#1521 postgis: Drop EL5 leftovers and fix package name for Fedora
  manifests/params.pp
Labels: community
