Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2023-10, with the labels that each got.

#1450 Add Server Instance Feature
  README.md
  REFERENCE.md
  lib/puppet/provider/postgresql_conf/parsed.rb
  lib/puppet/provider/postgresql_conf/ruby.rb
  lib/puppet/type/postgresql_conf.rb
  manifests/server.pp
  manifests/server/config_entry.pp
  manifests/server/database.pp
  manifests/server/db.pp
  manifests/server/default_privileges.pp
  manifests/server/extension.pp
  manifests/server/grant.pp
  manifests/server/grant_role.pp
  manifests/server/instance/config.pp
  manifests/server/instance/late_initdb.pp
  manifests/server/instance/systemd.pp
  manifests/server/pg_hba_rule.pp
  manifests/server/reassign_owned_by.pp
  manifests/server/role.pp
  manifests/server/schema.pp
  manifests/server/tablespace.pp
  manifests/server_instance.pp
  spec/acceptance/server_instance_spec.rb
  spec/defines/server_instance_spec.rb
  spec/unit/provider/postgresql_conf/parsed_spec.rb
  spec/unit/provider/postgresql_conf/ruby_spec.rb
  spec/unit/type/postgresql_conf_spec.rb
Labels: feature, backwards-incompatible, community

#1514 Drop code for Debian without systemd
  manifests/params.pp
Labels: backwards-incompatible, community

#1529 Fix the `postgresql::postgresql_password()` function
  lib/puppet/functions/postgresql/postgresql_password.rb
Labels: bugfix, community

#1530 Fix `postgresql::default()` return value for unknown parameters
  functions/default.pp
  spec/functions/postgresql_default_spec.rb
Labels: community

#1537 dnfmodule: update documentation about affected OSes
  REFERENCE.md
  manifests/dnfmodule.pp
  manifests/globals.pp
Labels: community

#1546 postgresql_conf: add spec tests for value param
  spec/unit/type/postgresql_conf_spec.rb
Labels: maintenance, community

#1544 postgresql_conf: Fix regex for value param and add tests
  lib/puppet/type/postgresql_conf.rb
  spec/unit/type/postgresql_conf_spec.rb
Labels: community
