Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2023-05, with the labels that each got.

#1428 (CONT-949) - Bump stdlib dependency
  metadata.json
Labels: bugfix

#1430 (CONT-950) - Fix mismatched data types
  lib/puppet/provider/postgresql_conf/parsed.rb
  manifests/server.pp
  manifests/server/config_entry.pp
  manifests/server/instance/config.pp
  spec/defines/server/config_entry_spec.rb
  spec/unit/provider/postgresql_conf/parsed_spec.rb
Labels: bugfix

#1433 (#1432) - Fix `Unable to mark 'unless' as sensitive`
  lib/puppet/type/postgresql_psql.rb
Labels: bugfix, community

#1434 (GH-1426) - Update value to accept array
  manifests/server/config_entry.pp
Labels: bugfix

#1437 pdksync - (CONT-930) - Roll out new changelog generator
  .github/workflows/auto_release.yml
  .github/workflows/release_prep.yml
Labels: maintenance

#1439 pdksync - (CONT-1001) Add litmus ~> 1.0
  Gemfile
Labels: maintenance
