Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2023-07, with the labels that each got.

#1451 add missing parameters to initdb
  manifests/server.pp
  manifests/server/initdb.pp
  manifests/server/instance/initdb.pp
Labels: community

#1454 implement key parameter for config_entry defined resource
  manifests/server/config_entry.pp
  manifests/server/instance/config.pp
  spec/classes/server/config_spec.rb
  spec/classes/server_spec.rb
Labels: community

#1455 Make anchors in defined resources unique
  manifests/server/instance/late_initdb.pp
  manifests/server/instance/service.pp
Labels: community

#1457 Fix log directory config entry name
  manifests/server/instance/config.pp
Labels: community

#1421 Add default version for Fedora 37, 38
  manifests/globals.pp
Labels: community

#1458 pdksync - (maint) - Replace legacy facts in spec/default_facts.yml
  spec/default_facts.yml
Labels: maintenance

#1459 pdksync - (CONT-1219) - fail ci for puppetlabs members if no label
  .github/workflows/labeller.yml
Labels: maintenance

#1460 Add Debian 12 compatibility
  manifests/globals.pp
  metadata.json
Labels: feature, community

#1461 maint: removing debian 12 from metadata
  metadata.json
Labels: maintenance

#1462 (CAT-1262)-updated legacy repo for SUSE
  spec/spec_helper_acceptance_local.rb
Labels: bugfix
