Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2023-04, with the labels that each got.

#1412 pdksync - (CONT-844) - Update .sync.yml
  .sync.yml
Labels: maintenance

#1415 (maint) - Release prep v8.3.0
  CHANGELOG.md
  Rakefile
  metadata.json
Labels: maintenance

#1416 (maint) - Release prep v9.0.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#1420 Fix wrong data type for `data_checksums` parameter
  REFERENCE.md
  manifests/globals.pp
  manifests/server.pp
Labels: bugfix, community

#1424 pdksync - (CONT-677) - set rubocop target to 2.6
  .rubocop.yml
  .rubocop_todo.yml
Labels: maintenance

#1425 Remove has_key usage
  manifests/server/database.pp
  manifests/server/default_privileges.pp
  manifests/server/extension.pp
  manifests/server/grant.pp
  manifests/server/reassign_owned_by.pp
  manifests/server/role.pp
  manifests/server/schema.pp
  manifests/server/tablespace.pp
Labels: community
