Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2023-02, with the labels that each got.

#1395 pdksync - (CONT-211) Adding mend config
  .github/workflows/mend.yml
Labels: maintenance

#1396 Cleanup Systemd drop-in file handling
  .fixtures.yml
  manifests/params.pp
  manifests/server/instance/config.pp
  manifests/server/instance/systemd.pp
  metadata.json
  spec/classes/server/config_spec.rb
  spec/classes/server_spec.rb
  spec/default_facts.yml
  spec/defines/server/config_entry_spec.rb
  templates/systemd-override.erb
Labels: community

#1399 convert ERB templates to EPP
  manifests/server/instance/systemd.pp
  manifests/server/pg_hba_rule.pp
  manifests/server/pg_ident_rule.pp
  manifests/server/recovery.pp
  templates/pg_dump.sh.epp
  templates/pg_hba_rule.conf
  templates/pg_hba_rule.conf.epp
  templates/pg_ident_rule.conf
  templates/pg_ident_rule.conf.epp
  templates/recovery.conf.epp
  templates/recovery.conf.erb
  templates/systemd-override.conf.epp
  templates/systemd-override.erb
Labels: feature, community

#1400 deprecate old code managing sysconfig files
  manifests/server/config_entry.pp
  manifests/server/instance/config.pp
Labels: community

#1397 (CONT-361) Syntax update
  .puppet-lint.rc
  .sync.yml
  Rakefile
  manifests/backup/pg_dump.pp
  manifests/client.pp
  manifests/dnfmodule.pp
  manifests/globals.pp
  manifests/lib/devel.pp
  manifests/lib/docs.pp
  manifests/lib/java.pp
  manifests/lib/perl.pp
  manifests/lib/python.pp
  manifests/repo.pp
  manifests/server.pp
  manifests/server/config_entry.pp
  manifests/server/contrib.pp
  manifests/server/database.pp
  manifests/server/database_grant.pp
  manifests/server/db.pp
  manifests/server/default_privileges.pp
  manifests/server/extension.pp
  manifests/server/grant.pp
  manifests/server/grant_role.pp
  manifests/server/instance/config.pp
  manifests/server/instance/initdb.pp
  manifests/server/instance/late_initdb.pp
  manifests/server/instance/passwd.pp
  manifests/server/instance/reload.pp
  manifests/server/instance/service.pp
  manifests/server/pg_ident_rule.pp
  manifests/server/plperl.pp
  manifests/server/plpython.pp
  manifests/server/postgis.pp
  manifests/server/reassign_owned_by.pp
  manifests/server/recovery.pp
  manifests/server/role.pp
  manifests/server/schema.pp
  manifests/server/table_grant.pp
  manifests/server/tablespace.pp
  manifests/validate_db_connection.pp
Labels: feature

#1403 (MAINT) - update pdk release image
  .github/workflows/auto_release.yml
Labels: maintenance
