Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2023-01, with the labels that each got.

#1385 pdksync - (CONT-494) Pin github_changelog_generator and JSON gem versions
  .sync.yml
  Gemfile
  metadata.json
Labels: maintenance

#1382 Add multi instance support, refactoring config.pp (1/x)
  manifests/server/config.pp
  manifests/server/instance_config.pp
  manifests/server/recovery.pp
  spec/defines/server/instance_config.rb
Labels: community

#1387 remove debian 8 and 9 corpses
  manifests/globals.pp
  spec/defines/server/default_privileges_spec.rb
  spec/spec_helper_local.rb
Labels: community

#1388 Ubuntu 14/16/17: Drop code leftovers
  manifests/globals.pp
Labels: community

#1383 Add multi instance support, refactoring initdb.pp (2/x)
  manifests/server/initdb.pp
  manifests/server/instance_initdb.pp
  spec/defines/server/instance_initdb.rb
Labels: community

#1384 Add multi instance support, refactoring late_initdb.pp (3/x)
  manifests/server/instance_late_initdb.pp
  manifests/server/late_initdb.pp
  spec/defines/server/instance_late_initdb.rb
Labels: community

#1381 Archlinux client and server package names were swapped around
  manifests/params.pp
Labels: bugfix, community

#1390 .fixtures.yml: Cleanup Puppet 5 leftovers
  .fixtures.yml
Labels: community

#1389 Add multi instance support, refactoring service.pp (4/x)
  manifests/server/instance_service.pp
  manifests/server/service.pp
  spec/defines/server/instance_service.rb
Labels: community

#1391 Add multi instance support, refactoring password.pp (5/x)
  manifests/server/instance_passwd.pp
  manifests/server/passwd.pp
  spec/defines/server/instance_passwd.rb
Labels: community

#1393 postgresql instances move and rename defines (7/x)
  manifests/server/config.pp
  manifests/server/initdb.pp
  manifests/server/instance/config.pp
  manifests/server/instance/initdb.pp
  manifests/server/instance/late_initdb.pp
  manifests/server/instance/passwd.pp
  manifests/server/instance/reload.pp
  manifests/server/instance/service.pp
  manifests/server/late_initdb.pp
  manifests/server/passwd.pp
  manifests/server/reload.pp
  manifests/server/service.pp
  spec/defines/server/instance/config.rb
  spec/defines/server/instance/initdb.rb
  spec/defines/server/instance/late_initdb.rb
  spec/defines/server/instance/passwd.rb
  spec/defines/server/instance/reload.rb
  spec/defines/server/instance/service.rb
Labels: community

#1394 postgresql instances fix parameter indention server::instance::passwd (8/x)
  manifests/server/instance/passwd.pp
Labels: community
