Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2024-01, with the labels that each got.

#1561 support for a custom apt source release
  data/os/Ubuntu/18.04.yaml
  manifests/globals.pp
  manifests/repo.pp
  manifests/repo/apt_postgresql_org.pp
  spec/classes/repo_spec.rb
Labels: bugfix

#1567 Remove non-portable source commands
  spec/spec_helper_acceptance_local.rb
Labels: maintenance, community

#1566 update GPG key
  files/RPM-GPG-KEY-PGDG
  files/RPM-GPG-KEY-PGDG-7
  manifests/repo/yum_postgresql_org.pp
Labels: community
