Repository puppetlabs/puppetlabs-postgresql, pull requests merged in 2024-04, with the labels that each got.

#1587 client.pp: Purge trailing whitespace
  manifests/client.pp
Labels: community

#1563 Use modern APT keyrings on Debian family; require puppetlabs/apt 9.2
  files/ACCC4CF8.asc
  manifests/repo/apt_postgresql_org.pp
  metadata.json
Labels: feature, community

#1586 pdksync - update mend to work on cron
  .github/workflows/mend.yml
Labels: maintenance

#1589 acceptance tests: ensure code is idempotent
  spec/acceptance/server_instance_spec.rb
Labels: bugfix

#1592 .fixtures.yml: unpin puppet_agent dependency
  .fixtures.yml
Labels: community

#1488 List Debian 12 as supported system
  metadata.json
Labels: feature, community

#1540 (#1532) Replace ParserError with Puppet::Error
  lib/puppet/provider/postgresql_conf/ruby.rb
  spec/unit/provider/postgresql_conf/ruby_spec.rb
Labels: community

#1588 Fix instance reload
  manifests/server/config_entry.pp
  manifests/server/database.pp
  manifests/server/database_grant.pp
  manifests/server/db.pp
  manifests/server/instance/config.pp
  manifests/server/instance/reload.pp
  manifests/server/instance/systemd.pp
  manifests/server/table_grant.pp
  manifests/server_instance.pp
  spec/classes/server_spec.rb
  spec/defines/server/config_entry_spec.rb
Labels: bugfix, community
